name: Deploy action
description: Deploy action
inputs:
  arch:
    description: 'Target architecture (x64 or x86)'
    required: true
    default: 'x64'
runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@v4
      id: upload-artifact-1
      with:
        name: ${{ env.SkiaSharpName }}.7z
        path: ${{ env.SkiaSharpName }}.7z

    - uses: actions/upload-artifact@v4
      id: upload-artifact-2
      with:
        name: ${{ env.HarfBuzzSharpName }}.7z
        path: ${{ env.HarfBuzzSharpName }}.7z

    - uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ env.SkiaSharpName }}.7z
        subject-digest: sha256:${{ steps.upload-artifact-1.outputs.artifact-digest }}

    - uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ env.HarfBuzzSharpName }}.7z
        subject-digest: sha256:${{ steps.upload-artifact-2.outputs.artifact-digest }}

    - name: Prerelease artifacts
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')  && contains(github.ref, '-pre')
      with:
        prerelease: true
        files: |
          ${{ env.SkiaSharpName }}.7z
          ${{ env.HarfBuzzSharpName }}.7z

    - name: Release artifacts
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')  && !contains(github.ref, '-pre')
      with:
        files: |
          ${{ env.SkiaSharpName }}.7z
          ${{ env.HarfBuzzSharpName }}.7z
