name: build-skia-2.88.9
on:
  push:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - "args.gn"
      - "args_x86.gn"
defaults:
  run:
    shell: nu {0}

env:
  SkiaSharpVersion: 2.88.9
jobs:
  build:
    runs-on: windows-2022
    permissions:
      id-token: write
      attestations: write
      contents: write
    strategy:
      matrix:
        arch: [x64, x86]
    steps:
      - uses: actions/checkout@v4
      - name: Set Architecture Environment
        shell: pwsh
        run: |
          if ("${{ matrix.arch }}" -eq "x86") {
            echo "VSCMD_ARG_HOST_ARCH=x86" >> $env:GITHUB_ENV
            echo "VSCMD_ARG_TGT_ARCH=x86" >> $env:GITHUB_ENV
            echo "PROCESSOR_ARCHITECTURE=x86" >> $env:GITHUB_ENV
          } else {
            echo "VSCMD_ARG_HOST_ARCH=x64" >> $env:GITHUB_ENV
            echo "VSCMD_ARG_TGT_ARCH=x64" >> $env:GITHUB_ENV
          }
      - uses: ./.github/actions/setup
        with:
          arch: ${{ matrix.arch }}
      - name: Install LLVM 21
        shell: pwsh
        run: winget install --id LLVM.LLVM --accept-package-agreements --accept-source-agreements --disable-interactivity
      - uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch }}
      - uses: ./.github/actions/deploy
        with:
          arch: ${{ matrix.arch }}
